# Site Settings
title: "Paul's Site"
description: "My personal Jekyll site built with So Simple"
url: "https://pauldavidfisher.github.io"
baseurl: "/paul-blog"
locale: en-US

# Theme
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"

# Author
author:
  name: Paul
  
# Logo/Avatar
logo: /images/yin-yang.svg  # Path to your logo

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: /page:num/

# Reading Settings
read_time: true
words_per_minute: 200

# Navigation
navigation:
  - title: Posts
    url: /posts/
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/
  - title: Recipes
    url: /recipes/
  - title: Search
    url: /search/